const accountType = {
    FIND_BY_ID_EMAIL_PHONENUM_ACCOUNT: 'FIND_BY_ID_EMAIL_PHONENUM_ACCOUNT',
    SHOW_PAGE_BY_TYPE: 'SHOW_PAGE_BY_TYPE',
    ERROR_ACTION: 'ERROR_ACTION',
}

export default accountType