const accountType = {
    FIND_BY_ID_EMAIL_PHONENUM_ACCOUNT: 'FIND_BY_ID_EMAIL_PHONENUM_ACCOUNT',
    SHOW_PAGE_BY_TYPE: 'SHOW_PAGE_BY_TYPE',
    DO_UPDATE_CUSTOMER: 'DO_UPDATE_CUSTOMER',
    DO_CREATE_ACCOUNT_INTERNAL: 'DO_CREATE_ACCOUNT_INTERNAL',
    ERROR_ACTION: 'ERROR_ACTION',
}

export default accountType