const reservationTypes = {
    CREATE_RESERVATION_ACTION: "CREATE_RESERVATION_ACTION",
    SET_ROOMS_ID_ACTION: "SET_ROOMS_ID_ACTION",
    SET_SERVICES_ACTION: "SET_SERVICES_ACTION",
    CANCEL_BY_ID_ACTION: "CANCEL_BY_ID_ACTION",
    ERROR_ACTION: "ERROR_ACTION",
}

export default reservationTypes