const reservationTypes = {
    CREATE_RESERVATION_ACTION: "CREATE_RESERVATION_ACTION",
    SET_ROOMS_ID_ACTION: "SET_ROOMS_ID_ACTION",
    SET_SERVICES_ACTION: "SET_SERVICES_ACTION",
    CANCEL_BY_ID_ACTION: "CANCEL_BY_ID_ACTION",
    FIND_FOR_TRANSACTION_ACTION: "FIND_FOR_TRANSACTION_ACTION",

    ERROR_CREATE_RESERVATION_ACTION: "ERROR_CREATE_RESERVATION_ACTION",
    ERROR_CANCEL_BY_ID_ACTION: "ERROR_CANCEL_BY_ID_ACTION",
    ERROR_FIND_FOR_TRANSACTION_ACTION: "ERROR_FIND_FOR_TRANSACTION_ACTION",

    RESET_RESERVATION_ROOM: "RESET_RESERVATION_ROOM",
}

export default reservationTypes