const roomtypeTypes = {
    SHOW_ROOMTYPE_LIST_ACTION: 'SHOW_ROOMTYPE_LIST_ACTION',
    SHOW_ROOMTYPE_BY_AVATAR_STATE_LIST_ACTION: 'SHOW_ROOMTYPE_BY_AVATAR_STATE_LIST_ACTION',
    FIND_ROOMTYPE_BY_ID_ACTION: 'FIND_ROOMTYPE_BY_ID_ACTION',
    ERROR_ACTION: 'ERROR_ACTION',
}

export default roomtypeTypes