const roomtypePhotoTypes = {
    SHOW_ROOMTYPE_PHOTO_BY_ID_ROOMTYPE : 'SHOW_ROOMTYPE_PHOTO_BY_ID_ROOMTYPE',
    SET_ROOMTYPE_PHOTO_ACTIVE : 'SET_ROOMTYPE_PHOTO_ACTIVE',
    ERROR_ACTION: 'ERROR_ACTION',
}
export default roomtypePhotoTypes