const roomtypeTypes = {
    SHOW_ROOMTYPE_LIST_ACTION: 'SHOW_ROOMTYPE_LIST_ACTION',
    SHOW_ROOMTYPE_BY_AVATAR_STATE_LIST_ACTION: 'SHOW_ROOMTYPE_BY_AVATAR_STATE_LIST_ACTION',
    FIND_ROOMTYPE_BY_ID_ACTION: 'FIND_ROOMTYPE_BY_ID_ACTION',
    CREATE_ROOMTYPE_ACTION: 'CREATE_ROOMTYPE_ACTION',
    DELETE_ROOMTYPE_BY_ID_ACTION: 'DELETE_ROOMTYPE_BY_ID_ACTION',
    UPDATE_ROOMTYPE_ACTION: 'UPDATE_ROOMTYPE_ACTION',
    ERROR_ACTION: 'ERROR_ACTION',
    SHOW_ROOMTYPE_PUBLIC: 'SHOW_ROOMTYPE_PUBLIC',
}

export default roomtypeTypes