const roomTypes = {
    SHOW_ROOMS_ACTION: 'SHOW_ROOMS_ACTION',
    ERROR_ACTION: 'ERROR_ACTION',
    SHOW_ROOM_DETAILS_ACTION: 'SHOW_ROOM_DETAILS_ACTION',
    CHECK_ROOM_EMPTY_ACTION: 'CHECK_ROOM_EMPTY_ACTION'
}

export default roomTypes