const roomTypes = {
    FIND_ALL_ACTION: 'FIND_ALL_ACTION',
    SHOW_ROOMS_ACTION: 'SHOW_ROOMS_ACTION',
    SHOW_ROOM_DETAILS_ACTION: 'SHOW_ROOM_DETAILS_ACTION',
    CHECK_ROOM_EMPTY_ACTION: 'CHECK_ROOM_EMPTY_ACTION',
    SAVE_ROOM_ACTION: 'SAVE_ROOM_ACTION',


    ERROR_FIND_ALL_ACTION: 'ERROR_FIND_ALL_ACTION',
    ERROR_SHOW_ROOM_DETAILS_ACTION: 'ERROR_SHOW_ROOM_DETAILS_ACTION',
    ERROR_SHOW_ROOMS_ACTION: 'ERROR_SHOW_ROOMS_ACTION',
    ERROR_CHECK_ROOM_EMPTY_ACTION: 'ERROR_CHECK_ROOM_EMPTY_ACTION',
}

export default roomTypes