const serviceTypes = {
    FIND_ALL_ACTION: 'FIND_ALL_ACTION',
    ERROR_ACTION: 'ERROR_ACTION',
    FIND_ALL_SERVICES_LIST: 'FIND_ALL_SERVICES_LIST',
    DO_CREATE_SERVICE: 'DO_CREATE_SERVICE',
}
export default serviceTypes