const transactionTypes = {
    GET_TRANSACTIONS_LIST: 'GET_TRANSACTIONS_LIST',
    CREATE_TRANSACTION_PAYMENT_ACTION: "CREATE_TRANSACTION_PAYMENT_ACTION",
    ERROR_ACTION: "ERROR_ACTION",
    GET_TRANSACTIONS_LIST_FOR_CUSTOMER: "GET_TRANSACTIONS_LIST_FOR_CUSTOMER",
    FIND_BY_ID_TRANSACTION: "FIND_BY_ID_TRANSACTION"
}

export default transactionTypes