const transactionTypes = {
    GET_TRANSACTIONS_LIST: 'GET_TRANSACTIONS_LIST',
    CREATE_TRANSACTION_PAYMENT_ACTION: "CREATE_TRANSACTION_PAYMENT_ACTION",
    ERROR_ACTION: "ERROR_ACTION",
}

export default transactionTypes